### ISSUE TITLE
Pravice za javnost

### ISSUE THREAD

**Issue by majbc1999** [matejbolta/zdravstvo-na-daljavo#5]
Živjo! Malo sem pregledoval, kako vama gre s projektom in imam manjšo pripombo. Vajina spletna stran bo morala delovati za vsakogar, zato v datoteki `zdravstvo_na_daljavo.py` ne smeta uvoziti neposredno `auth`a. V datoteki `auth.py` so namreč vajini osebni podatki in zato zame spletne strani niti ne zažene. Uvozita raje datoteko `auth_public.py`:
```python
import auth_public as auth
```
Potem bo vsak lahko odprl vajino spletno stran. Nato morata še paziti, da dodelita ustrezne pravice uporabniku `javnost`. Na primer, zaenkrat ne deluje dodajanje pacientov (uporabnik `javnost` nima pravice dodajati v tabelo `pacient`). Torej, uporabniku `javnost` morata dodeliti vse pravice, ki jih bo vajina spletna stran uporabljala.

**Comment by matejbolta** [comment]
Tako je bilo tudi planirano, hvala za opozorilo.
