### ISSUE TITLE
Končanje projekta

### ISSUE THREAD

**Issue by majbc1999** [matejbolta/zdravstvo-na-daljavo#6]
Živjo! Janoš mi je rekel, da sta končala projekt in ga mislita oddati. ˙

Pregledal sem ga in opazil, da vama `binder` ne deluje. To se vama zgodi, ker nedosledno uporabljata redirectanje s funkcijo `url`. Da bo binder v celoti deloval, morata **vse** preusmeritve narediti s funkcijo `url`. Prav tako funkciji `url` ne smeta podajati poti, temveč ime funkcije na poti. Na primer, treba bo spremeniti
```python
@get('/')
def index():
    # preko piškotka ugotovimo, če je uporabnik že prijavljen ali pa ga moramo preusmeriti na prijavo
    user = request.get_cookie('user', secret=SECRET)
    if user is not None:
        if user[0] == 'z':
            return template('index.tpl', message=None)
        else:
            redirect(url('/moj_profil/'))
    redirect('/login/')
```
in narediti:
```python
@get('/')
def index():
    # preko piškotka ugotovimo, če je uporabnik že prijavljen ali pa ga moramo preusmeriti na prijavo
    user = request.get_cookie('user', secret=SECRET)
    if user is not None:
        if user[0] == 'z':
            return template('index.tpl', message=None)
        else:
            redirect(url('moj_profil'))
    redirect(url('login_get'))
```

**Comment by matejbolta** [comment]
Hvala za popravek, sedaj je težava odpravljena in binder deluje.

**Comment by majbc1999** [comment]
Sedaj sem preveril še vsebino. Dobro bi bilo, da v `README` dodata še kakšne podatke za prijavo, tako za zdravnika, kakor tudi za pacienta (da ne bo treba gledati v bazo). Prosim, izberita tako, da sta zdravnik in pacient povezana (da bom lažje videl, če pošiljanje izvidov in receptov deluje). 

Kar me še moti, je to, da je treba pritisniti ENTER, ko želim prikazati samo zdravstvene domove z več kot $n$ oseb. Bodisi dodajta gumb, da bo uporabnik videl, da mora pritisniti, ali pa s pomočjo JavaScripta naredita, da se bo avtomatsko posodabljalo.

Poleg tega bi bilo dobro, da se, ko zdravnik doda novega pacienta, avtomatsko dodajo neki prijavni podatki v bazo (sicer se pacient nikakor ne more prijaviti). Na primer, uporabniško ime in geslo naj sta kar emšo (ali kaj podobnega).

Ostalo se mi zdi zaenkrat v redu. Ko popravita teh par reči, mi znova napišita, da ponovno pregledam.

**Comment by lukasimcic** [comment]
Hvala za opozorilo. Napisano sva popravila.

**Comment by jaanos** [comment]
Sem pregledal - glede na to, da projekt deluje, bom dodal povezavo na repozitorij za zagovore. Če se še nista, se lahko z @alenFMF domenita za termin zagovora. Če bosta še kaj spreminjala, mi javita, da posodobim povezavo.

Svetoval bi le, da gesel v bazo ne shranjujeta v čisti obliki, pač pa shranjujeta zgostitve (poglejta, kako so to naredili ostali). Vidim, da sta upoštevala predlog, ki ga je podal @majbc1999, in kot pacientovo geslo uporabila številko zdravstvenega zavarovanja - potem bi bilo smiselno, da to v obrazcu za dodajanje pacianta tudi predstavita kot geslo.

**Comment by lukasimcic** [comment]
Hvala za opombe, sva dodala zgostitve gesel. Dodala sva tudi navodila za prijavo, kjer je opisano, da je pacientovo geslo številka njegovega zdravstvenega zavarovanja. Ne vem pa, če bi bilo smiselno to informacijo podati zdravniku ob prijavi novega pacienta, saj je to stvar pacienta, zdravnik zgolj vpisuje podatke pacienta.

**Comment by lukasimcic** [comment]
Sem naredil še nekaj manjših sprememb, samo sporočam za posodobitev povezave.

**Comment by jaanos** [comment]
V redu, sem posodobil povezavo.
